### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Portalboy07** [haseemisaac/Dialogflow2Discord#6]
(node:59195) UnhandledPromiseRejectionWarning: Error: An invalid token was provided.
    at Promise (/home/portalboy/Загрузки/Dialogflow2Discord-master/node_modules/discord.js/src/client/rest/RESTMethods.js:33:44)
    at new Promise (<anonymous>)
    at RESTMethods.login (/home/portalboy/Загрузки/Dialogflow2Discord-master/node_modules/discord.js/src/client/rest/RESTMethods.js:32:12)
    at Client.login (/home/portalboy/Загрузки/Dialogflow2Discord-master/node_modules/discord.js/src/client/Client.js:277:30)
    at Object.<anonymous> (/home/portalboy/Загрузки/Dialogflow2Discord-master/index.js:40:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:59195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What's wrong ? Token is correct

**Comment by halixness** [comment]
Same error here

**Comment by NadineLaakso** [comment]
Did you create a .env file with the different tokens like I used them in the code? I also recommend switching to the new dialogflow version. I put in another pull requests for the updated code.

**Comment by Portalboy07** [comment]
yes
